sudo: required
dist: eoan
language: java
jdk:
  - oraclejdk11
python:
  - "3.6"    
services: docker
before_install:
  - sudo apt-get update
  - cd filipeapp
  - echo "Starting maven package"
  - mvn clean package
  - cd ..
script:
  - echo "OK"
  - docker-compose build
before_deploy:
 - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker tag filipeapp: latest fcmunhoz/filipeapp:$TRAVIS_JOB_ID;
    docker push fcmunhoz/filipeapp: $TRAVIS_JOB_ID;
  on:
    branch: master
after_success:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 449879531725.dkr.ecr.us-east-1.amazonaws.com
  - docker tag filipeapp:latest $IMAGE_REPO_URL:$TRAVIS_JOB_ID
  - docker push $IMAGE_REPO_URL:$TRAVIS_JOB_ID
  - add-apt-repository ppa:eugenesan/ppa
  - apt-get update
  - apt-get install jq -y  
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy
  - echo "AWS ECS-Deploy Setup Completed"
  - ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMAGE_REPO_URL:$TRAVIS_JOB_ID -r $AWS_DEFAULT_REGION -t 240
notifications:
  email: false
