version: '3.4'

services:
    filipeapp:
        image: filipeapp
        restart: always
        build: ./filipeapp
        working_dir: /filipeapp
        environment:
            TZ: America/Sao_Paulo
            SPRING-BOOT-ENVIRONMENT: Production
        ports:
          - "8080:8080"
        command: mvn spring-boot:run
        networks:
          - udemy-network
networks:
    udemy-network:
        driver: bridge
